TRAIN:
  LR_WARM_UP: False
  CLIP_GRAD: True
  END2END: False
  BATCH_SIZE: 4
  DO_VALIDATION: True
DATA:
  IMAGE_MIN_DIM: 800
  IMAGE_MAX_DIM: 1024
DEV:
  SWITCH: True
  BUFFER_SIZE: 1  # use all history
  LOSS_CHOICE: 'ot'
  OT_ONE_DIM_FORM: 'conv'
  LOSS_FAC: 1.
  ASSIGN_BOX_ON_ALL_SCALE: False
  BIG_SUPERVISE: False
  BIG_LOSS_FAC: 1.
  BIG_FC_INIT: 'coco_pretrain'
  MULTI_UPSAMPLER: False
ROIS:
  ASSIGN_ANCHOR_BASE: 224.  # default
MODEL:
  INIT_FILE_CHOICE: 'coco_pretrain'
CTRL:
  QUICK_VERIFY: True
MISC:
  USE_VISDOM: True
  VIS:
    PORT: 2035
