TRAIN:
  LR_WARM_UP: False
  CLIP_GRAD: True
  END2END: False
  BATCH_SIZE: 8
  DO_VALIDATION: True
  FPN_OT_LOSS: True
  FPN_OT_LOSS_FAC: 1.
DATA:
  IMAGE_MIN_DIM: 800
  IMAGE_MAX_DIM: 1024
DEV:
  SWITCH: True
  BUFFER_SIZE: 1  # use all history
  LOSS_CHOICE: 'l2'
  LOSS_FAC: 100.
  STRUCTURE: 'beta'
  ASSIGN_BOX_ON_ALL_SCALE: False
  DIS_UPSAMPLER: False
  UPSAMPLE_FAC: 1.
  BIG_FEAT_DETACH: True
  INST_LOSS: True
CTRL:
  QUICK_VERIFY: False
MISC:
  USE_VISDOM: True
  VIS:
    PORT: 2176

