TRAIN:
  LR_WARM_UP: False
  CLIP_GRAD: True
  END2END: False
  BATCH_SIZE: 4
  DO_VALIDATION: True
DATA:
  IMAGE_MIN_DIM: 800
  IMAGE_MAX_DIM: 1024
DEV:
  SWITCH: True
  BUFFER_SIZE: 1  # use all history
  LOSS_CHOICE: 'l1'
  LOSS_FAC: .5
  ASSIGN_BOX_ON_ALL_SCALE: True
ROIS:
  ASSIGN_ANCHOR_BASE: 100.
MODEL:
  INIT_FILE_CHOICE: 'coco_pretrain'
CTRL:
  QUICK_VERIFY: True
